// Code generated by protoc-gen-go.
// source: examples/example.proto
// DO NOT EDIT!

/*
Package examples is a generated protocol buffer package.

It is generated from these files:
	examples/example.proto

It has these top-level messages:
	SimpleMessage
	NumberMessage
	RepeatedNumberMessage
	NestedMessage
	EnumMessage
	Oneof
	NormalOneof
	OneofMessage
	NormalOneofMessage
	MapMessage
	WellKnownTypeMessage
*/
package examples

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/kazegusuri/go-proto-anonymizer"
import google_protobuf1 "github.com/golang/protobuf/ptypes/duration"
import google_protobuf2 "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NumericEnum int32

const (
	NumericEnum_ZERO NumericEnum = 0
	NumericEnum_ONE  NumericEnum = 1
	NumericEnum_TWO  NumericEnum = 2
)

var NumericEnum_name = map[int32]string{
	0: "ZERO",
	1: "ONE",
	2: "TWO",
}
var NumericEnum_value = map[string]int32{
	"ZERO": 0,
	"ONE":  1,
	"TWO":  2,
}

func (x NumericEnum) String() string {
	return proto.EnumName(NumericEnum_name, int32(x))
}
func (NumericEnum) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type AliasedEnum int32

const (
	AliasedEnum_UNKNOWN AliasedEnum = 0
	AliasedEnum_STARTED AliasedEnum = 1
	AliasedEnum_RUNNING AliasedEnum = 1
)

var AliasedEnum_name = map[int32]string{
	0: "UNKNOWN",
	1: "STARTED",
	// Duplicate value: 1: "RUNNING",
}
var AliasedEnum_value = map[string]int32{
	"UNKNOWN": 0,
	"STARTED": 1,
	"RUNNING": 1,
}

func (x AliasedEnum) String() string {
	return proto.EnumName(AliasedEnum_name, int32(x))
}
func (AliasedEnum) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type EnumMessage_Nested int32

const (
	EnumMessage_UNKNOWN   EnumMessage_Nested = 0
	EnumMessage_PENDING   EnumMessage_Nested = 1
	EnumMessage_COMPLETED EnumMessage_Nested = 2
)

var EnumMessage_Nested_name = map[int32]string{
	0: "UNKNOWN",
	1: "PENDING",
	2: "COMPLETED",
}
var EnumMessage_Nested_value = map[string]int32{
	"UNKNOWN":   0,
	"PENDING":   1,
	"COMPLETED": 2,
}

func (x EnumMessage_Nested) String() string {
	return proto.EnumName(EnumMessage_Nested_name, int32(x))
}
func (EnumMessage_Nested) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

type SimpleMessage struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue" json:"string_value,omitempty"`
	BoolValue   bool   `protobuf:"varint,2,opt,name=bool_value,json=boolValue" json:"bool_value,omitempty"`
}

func (m *SimpleMessage) Reset()                    { *m = SimpleMessage{} }
func (m *SimpleMessage) String() string            { return proto.CompactTextString(m) }
func (*SimpleMessage) ProtoMessage()               {}
func (*SimpleMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SimpleMessage) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *SimpleMessage) GetBoolValue() bool {
	if m != nil {
		return m.BoolValue
	}
	return false
}

type NumberMessage struct {
	FloatValue    float32 `protobuf:"fixed32,1,opt,name=float_value,json=floatValue" json:"float_value,omitempty"`
	DoubleValue   float64 `protobuf:"fixed64,2,opt,name=double_value,json=doubleValue" json:"double_value,omitempty"`
	Int32Value    int32   `protobuf:"varint,3,opt,name=int32_value,json=int32Value" json:"int32_value,omitempty"`
	Int64Value    int64   `protobuf:"varint,4,opt,name=int64_value,json=int64Value" json:"int64_value,omitempty"`
	Uint32Value   uint32  `protobuf:"varint,5,opt,name=uint32_value,json=uint32Value" json:"uint32_value,omitempty"`
	Uint64Value   uint64  `protobuf:"varint,6,opt,name=uint64_value,json=uint64Value" json:"uint64_value,omitempty"`
	Sint32Value   int32   `protobuf:"zigzag32,7,opt,name=sint32_value,json=sint32Value" json:"sint32_value,omitempty"`
	Sint64Value   int64   `protobuf:"zigzag64,8,opt,name=sint64_value,json=sint64Value" json:"sint64_value,omitempty"`
	Fixed32Value  uint32  `protobuf:"fixed32,9,opt,name=fixed32_value,json=fixed32Value" json:"fixed32_value,omitempty"`
	Fixed64Value  uint64  `protobuf:"fixed64,10,opt,name=fixed64_value,json=fixed64Value" json:"fixed64_value,omitempty"`
	Sfixed32Value int32   `protobuf:"fixed32,11,opt,name=sfixed32_value,json=sfixed32Value" json:"sfixed32_value,omitempty"`
	Sfixed64Value int64   `protobuf:"fixed64,12,opt,name=sfixed64_value,json=sfixed64Value" json:"sfixed64_value,omitempty"`
}

func (m *NumberMessage) Reset()                    { *m = NumberMessage{} }
func (m *NumberMessage) String() string            { return proto.CompactTextString(m) }
func (*NumberMessage) ProtoMessage()               {}
func (*NumberMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NumberMessage) GetFloatValue() float32 {
	if m != nil {
		return m.FloatValue
	}
	return 0
}

func (m *NumberMessage) GetDoubleValue() float64 {
	if m != nil {
		return m.DoubleValue
	}
	return 0
}

func (m *NumberMessage) GetInt32Value() int32 {
	if m != nil {
		return m.Int32Value
	}
	return 0
}

func (m *NumberMessage) GetInt64Value() int64 {
	if m != nil {
		return m.Int64Value
	}
	return 0
}

func (m *NumberMessage) GetUint32Value() uint32 {
	if m != nil {
		return m.Uint32Value
	}
	return 0
}

func (m *NumberMessage) GetUint64Value() uint64 {
	if m != nil {
		return m.Uint64Value
	}
	return 0
}

func (m *NumberMessage) GetSint32Value() int32 {
	if m != nil {
		return m.Sint32Value
	}
	return 0
}

func (m *NumberMessage) GetSint64Value() int64 {
	if m != nil {
		return m.Sint64Value
	}
	return 0
}

func (m *NumberMessage) GetFixed32Value() uint32 {
	if m != nil {
		return m.Fixed32Value
	}
	return 0
}

func (m *NumberMessage) GetFixed64Value() uint64 {
	if m != nil {
		return m.Fixed64Value
	}
	return 0
}

func (m *NumberMessage) GetSfixed32Value() int32 {
	if m != nil {
		return m.Sfixed32Value
	}
	return 0
}

func (m *NumberMessage) GetSfixed64Value() int64 {
	if m != nil {
		return m.Sfixed64Value
	}
	return 0
}

type RepeatedNumberMessage struct {
	FloatValues    []float32 `protobuf:"fixed32,1,rep,packed,name=float_values,json=floatValues" json:"float_values,omitempty"`
	DoubleValues   []float64 `protobuf:"fixed64,2,rep,packed,name=double_values,json=doubleValues" json:"double_values,omitempty"`
	Int32Values    []int32   `protobuf:"varint,3,rep,packed,name=int32_values,json=int32Values" json:"int32_values,omitempty"`
	Int64Values    []int64   `protobuf:"varint,4,rep,packed,name=int64_values,json=int64Values" json:"int64_values,omitempty"`
	Uint32Values   []uint32  `protobuf:"varint,5,rep,packed,name=uint32_values,json=uint32Values" json:"uint32_values,omitempty"`
	Uint64Values   []uint64  `protobuf:"varint,6,rep,packed,name=uint64_values,json=uint64Values" json:"uint64_values,omitempty"`
	Sint32Values   []int32   `protobuf:"zigzag32,7,rep,packed,name=sint32_values,json=sint32Values" json:"sint32_values,omitempty"`
	Sint64Values   []int64   `protobuf:"zigzag64,8,rep,packed,name=sint64_values,json=sint64Values" json:"sint64_values,omitempty"`
	Fixed32Values  []uint32  `protobuf:"fixed32,9,rep,packed,name=fixed32_values,json=fixed32Values" json:"fixed32_values,omitempty"`
	Fixed64Values  []uint64  `protobuf:"fixed64,10,rep,packed,name=fixed64_values,json=fixed64Values" json:"fixed64_values,omitempty"`
	Sfixed32Values []int32   `protobuf:"fixed32,11,rep,packed,name=sfixed32_values,json=sfixed32Values" json:"sfixed32_values,omitempty"`
	Sfixed64Values []int64   `protobuf:"fixed64,12,rep,packed,name=sfixed64_values,json=sfixed64Values" json:"sfixed64_values,omitempty"`
}

func (m *RepeatedNumberMessage) Reset()                    { *m = RepeatedNumberMessage{} }
func (m *RepeatedNumberMessage) String() string            { return proto.CompactTextString(m) }
func (*RepeatedNumberMessage) ProtoMessage()               {}
func (*RepeatedNumberMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RepeatedNumberMessage) GetFloatValues() []float32 {
	if m != nil {
		return m.FloatValues
	}
	return nil
}

func (m *RepeatedNumberMessage) GetDoubleValues() []float64 {
	if m != nil {
		return m.DoubleValues
	}
	return nil
}

func (m *RepeatedNumberMessage) GetInt32Values() []int32 {
	if m != nil {
		return m.Int32Values
	}
	return nil
}

func (m *RepeatedNumberMessage) GetInt64Values() []int64 {
	if m != nil {
		return m.Int64Values
	}
	return nil
}

func (m *RepeatedNumberMessage) GetUint32Values() []uint32 {
	if m != nil {
		return m.Uint32Values
	}
	return nil
}

func (m *RepeatedNumberMessage) GetUint64Values() []uint64 {
	if m != nil {
		return m.Uint64Values
	}
	return nil
}

func (m *RepeatedNumberMessage) GetSint32Values() []int32 {
	if m != nil {
		return m.Sint32Values
	}
	return nil
}

func (m *RepeatedNumberMessage) GetSint64Values() []int64 {
	if m != nil {
		return m.Sint64Values
	}
	return nil
}

func (m *RepeatedNumberMessage) GetFixed32Values() []uint32 {
	if m != nil {
		return m.Fixed32Values
	}
	return nil
}

func (m *RepeatedNumberMessage) GetFixed64Values() []uint64 {
	if m != nil {
		return m.Fixed64Values
	}
	return nil
}

func (m *RepeatedNumberMessage) GetSfixed32Values() []int32 {
	if m != nil {
		return m.Sfixed32Values
	}
	return nil
}

func (m *RepeatedNumberMessage) GetSfixed64Values() []int64 {
	if m != nil {
		return m.Sfixed64Values
	}
	return nil
}

type NestedMessage struct {
	NestedValue                *NestedMessage_Nested   `protobuf:"bytes,1,opt,name=nested_value,json=nestedValue" json:"nested_value,omitempty"`
	RepeatedNestedValues       []*NestedMessage_Nested `protobuf:"bytes,2,rep,name=repeated_nested_values,json=repeatedNestedValues" json:"repeated_nested_values,omitempty"`
	NormalNestedValue          *NestedMessage_Nested   `protobuf:"bytes,3,opt,name=normal_nested_value,json=normalNestedValue" json:"normal_nested_value,omitempty"`
	NormalRepeatedNestedValues []*NestedMessage_Nested `protobuf:"bytes,4,rep,name=normal_repeated_nested_values,json=normalRepeatedNestedValues" json:"normal_repeated_nested_values,omitempty"`
}

func (m *NestedMessage) Reset()                    { *m = NestedMessage{} }
func (m *NestedMessage) String() string            { return proto.CompactTextString(m) }
func (*NestedMessage) ProtoMessage()               {}
func (*NestedMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *NestedMessage) GetNestedValue() *NestedMessage_Nested {
	if m != nil {
		return m.NestedValue
	}
	return nil
}

func (m *NestedMessage) GetRepeatedNestedValues() []*NestedMessage_Nested {
	if m != nil {
		return m.RepeatedNestedValues
	}
	return nil
}

func (m *NestedMessage) GetNormalNestedValue() *NestedMessage_Nested {
	if m != nil {
		return m.NormalNestedValue
	}
	return nil
}

func (m *NestedMessage) GetNormalRepeatedNestedValues() []*NestedMessage_Nested {
	if m != nil {
		return m.NormalRepeatedNestedValues
	}
	return nil
}

type NestedMessage_Nested struct {
	Int32Value  int32  `protobuf:"varint,1,opt,name=int32_value,json=int32Value" json:"int32_value,omitempty"`
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue" json:"string_value,omitempty"`
}

func (m *NestedMessage_Nested) Reset()                    { *m = NestedMessage_Nested{} }
func (m *NestedMessage_Nested) String() string            { return proto.CompactTextString(m) }
func (*NestedMessage_Nested) ProtoMessage()               {}
func (*NestedMessage_Nested) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

func (m *NestedMessage_Nested) GetInt32Value() int32 {
	if m != nil {
		return m.Int32Value
	}
	return 0
}

func (m *NestedMessage_Nested) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

type EnumMessage struct {
	NumericEnumValue          NumericEnum          `protobuf:"varint,1,opt,name=numeric_enum_value,json=numericEnumValue,enum=kazegusuri.example.NumericEnum" json:"numeric_enum_value,omitempty"`
	RepeatedNumericEnumValues []NumericEnum        `protobuf:"varint,2,rep,packed,name=repeated_numeric_enum_values,json=repeatedNumericEnumValues,enum=kazegusuri.example.NumericEnum" json:"repeated_numeric_enum_values,omitempty"`
	AliasedEnumValue          AliasedEnum          `protobuf:"varint,3,opt,name=aliased_enum_value,json=aliasedEnumValue,enum=kazegusuri.example.AliasedEnum" json:"aliased_enum_value,omitempty"`
	NestedEnumValue           EnumMessage_Nested   `protobuf:"varint,4,opt,name=nested_enum_value,json=nestedEnumValue,enum=kazegusuri.example.EnumMessage_Nested" json:"nested_enum_value,omitempty"`
	RepeatedNestedEnumValues  []EnumMessage_Nested `protobuf:"varint,5,rep,packed,name=repeated_nested_enum_values,json=repeatedNestedEnumValues,enum=kazegusuri.example.EnumMessage_Nested" json:"repeated_nested_enum_values,omitempty"`
}

func (m *EnumMessage) Reset()                    { *m = EnumMessage{} }
func (m *EnumMessage) String() string            { return proto.CompactTextString(m) }
func (*EnumMessage) ProtoMessage()               {}
func (*EnumMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *EnumMessage) GetNumericEnumValue() NumericEnum {
	if m != nil {
		return m.NumericEnumValue
	}
	return NumericEnum_ZERO
}

func (m *EnumMessage) GetRepeatedNumericEnumValues() []NumericEnum {
	if m != nil {
		return m.RepeatedNumericEnumValues
	}
	return nil
}

func (m *EnumMessage) GetAliasedEnumValue() AliasedEnum {
	if m != nil {
		return m.AliasedEnumValue
	}
	return AliasedEnum_UNKNOWN
}

func (m *EnumMessage) GetNestedEnumValue() EnumMessage_Nested {
	if m != nil {
		return m.NestedEnumValue
	}
	return EnumMessage_UNKNOWN
}

func (m *EnumMessage) GetRepeatedNestedEnumValues() []EnumMessage_Nested {
	if m != nil {
		return m.RepeatedNestedEnumValues
	}
	return nil
}

type Oneof struct {
	// Types that are valid to be assigned to OneofValue:
	//	*Oneof_Int32Value
	//	*Oneof_StringValue
	OneofValue isOneof_OneofValue `protobuf_oneof:"oneof_value"`
}

func (m *Oneof) Reset()                    { *m = Oneof{} }
func (m *Oneof) String() string            { return proto.CompactTextString(m) }
func (*Oneof) ProtoMessage()               {}
func (*Oneof) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type isOneof_OneofValue interface {
	isOneof_OneofValue()
}

type Oneof_Int32Value struct {
	Int32Value int32 `protobuf:"varint,1,opt,name=int32_value,json=int32Value,oneof"`
}
type Oneof_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,oneof"`
}

func (*Oneof_Int32Value) isOneof_OneofValue()  {}
func (*Oneof_StringValue) isOneof_OneofValue() {}

func (m *Oneof) GetOneofValue() isOneof_OneofValue {
	if m != nil {
		return m.OneofValue
	}
	return nil
}

func (m *Oneof) GetInt32Value() int32 {
	if x, ok := m.GetOneofValue().(*Oneof_Int32Value); ok {
		return x.Int32Value
	}
	return 0
}

func (m *Oneof) GetStringValue() string {
	if x, ok := m.GetOneofValue().(*Oneof_StringValue); ok {
		return x.StringValue
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Oneof) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Oneof_OneofMarshaler, _Oneof_OneofUnmarshaler, _Oneof_OneofSizer, []interface{}{
		(*Oneof_Int32Value)(nil),
		(*Oneof_StringValue)(nil),
	}
}

func _Oneof_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Oneof)
	// oneof_value
	switch x := m.OneofValue.(type) {
	case *Oneof_Int32Value:
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Int32Value))
	case *Oneof_StringValue:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.StringValue)
	case nil:
	default:
		return fmt.Errorf("Oneof.OneofValue has unexpected type %T", x)
	}
	return nil
}

func _Oneof_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Oneof)
	switch tag {
	case 1: // oneof_value.int32_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.OneofValue = &Oneof_Int32Value{int32(x)}
		return true, err
	case 2: // oneof_value.string_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.OneofValue = &Oneof_StringValue{x}
		return true, err
	default:
		return false, nil
	}
}

func _Oneof_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Oneof)
	// oneof_value
	switch x := m.OneofValue.(type) {
	case *Oneof_Int32Value:
		n += proto.SizeVarint(1<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.Int32Value))
	case *Oneof_StringValue:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.StringValue)))
		n += len(x.StringValue)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type NormalOneof struct {
	// Types that are valid to be assigned to OneofValue:
	//	*NormalOneof_Int32Value
	//	*NormalOneof_StringValue
	OneofValue isNormalOneof_OneofValue `protobuf_oneof:"oneof_value"`
}

func (m *NormalOneof) Reset()                    { *m = NormalOneof{} }
func (m *NormalOneof) String() string            { return proto.CompactTextString(m) }
func (*NormalOneof) ProtoMessage()               {}
func (*NormalOneof) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type isNormalOneof_OneofValue interface {
	isNormalOneof_OneofValue()
}

type NormalOneof_Int32Value struct {
	Int32Value int32 `protobuf:"varint,1,opt,name=int32_value,json=int32Value,oneof"`
}
type NormalOneof_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,oneof"`
}

func (*NormalOneof_Int32Value) isNormalOneof_OneofValue()  {}
func (*NormalOneof_StringValue) isNormalOneof_OneofValue() {}

func (m *NormalOneof) GetOneofValue() isNormalOneof_OneofValue {
	if m != nil {
		return m.OneofValue
	}
	return nil
}

func (m *NormalOneof) GetInt32Value() int32 {
	if x, ok := m.GetOneofValue().(*NormalOneof_Int32Value); ok {
		return x.Int32Value
	}
	return 0
}

func (m *NormalOneof) GetStringValue() string {
	if x, ok := m.GetOneofValue().(*NormalOneof_StringValue); ok {
		return x.StringValue
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*NormalOneof) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _NormalOneof_OneofMarshaler, _NormalOneof_OneofUnmarshaler, _NormalOneof_OneofSizer, []interface{}{
		(*NormalOneof_Int32Value)(nil),
		(*NormalOneof_StringValue)(nil),
	}
}

func _NormalOneof_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*NormalOneof)
	// oneof_value
	switch x := m.OneofValue.(type) {
	case *NormalOneof_Int32Value:
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Int32Value))
	case *NormalOneof_StringValue:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.StringValue)
	case nil:
	default:
		return fmt.Errorf("NormalOneof.OneofValue has unexpected type %T", x)
	}
	return nil
}

func _NormalOneof_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*NormalOneof)
	switch tag {
	case 1: // oneof_value.int32_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.OneofValue = &NormalOneof_Int32Value{int32(x)}
		return true, err
	case 2: // oneof_value.string_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.OneofValue = &NormalOneof_StringValue{x}
		return true, err
	default:
		return false, nil
	}
}

func _NormalOneof_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*NormalOneof)
	// oneof_value
	switch x := m.OneofValue.(type) {
	case *NormalOneof_Int32Value:
		n += proto.SizeVarint(1<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.Int32Value))
	case *NormalOneof_StringValue:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.StringValue)))
		n += len(x.StringValue)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type OneofMessage struct {
	// Types that are valid to be assigned to OneofValue:
	//	*OneofMessage_Int32Value
	//	*OneofMessage_StringValue
	OneofValue                isOneofMessage_OneofValue `protobuf_oneof:"oneof_value"`
	OneofMessageValue         *Oneof                    `protobuf:"bytes,3,opt,name=oneof_message_value,json=oneofMessageValue" json:"oneof_message_value,omitempty"`
	RepeatedOneofValues       []*Oneof                  `protobuf:"bytes,4,rep,name=repeated_oneof_values,json=repeatedOneofValues" json:"repeated_oneof_values,omitempty"`
	NormalOneofMessageValue   *Oneof                    `protobuf:"bytes,5,opt,name=normal_oneof_message_value,json=normalOneofMessageValue" json:"normal_oneof_message_value,omitempty"`
	NormalRepeatedOneofValues []*Oneof                  `protobuf:"bytes,6,rep,name=normal_repeated_oneof_values,json=normalRepeatedOneofValues" json:"normal_repeated_oneof_values,omitempty"`
}

func (m *OneofMessage) Reset()                    { *m = OneofMessage{} }
func (m *OneofMessage) String() string            { return proto.CompactTextString(m) }
func (*OneofMessage) ProtoMessage()               {}
func (*OneofMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type isOneofMessage_OneofValue interface {
	isOneofMessage_OneofValue()
}

type OneofMessage_Int32Value struct {
	Int32Value int32 `protobuf:"varint,1,opt,name=int32_value,json=int32Value,oneof"`
}
type OneofMessage_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,oneof"`
}

func (*OneofMessage_Int32Value) isOneofMessage_OneofValue()  {}
func (*OneofMessage_StringValue) isOneofMessage_OneofValue() {}

func (m *OneofMessage) GetOneofValue() isOneofMessage_OneofValue {
	if m != nil {
		return m.OneofValue
	}
	return nil
}

func (m *OneofMessage) GetInt32Value() int32 {
	if x, ok := m.GetOneofValue().(*OneofMessage_Int32Value); ok {
		return x.Int32Value
	}
	return 0
}

func (m *OneofMessage) GetStringValue() string {
	if x, ok := m.GetOneofValue().(*OneofMessage_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *OneofMessage) GetOneofMessageValue() *Oneof {
	if m != nil {
		return m.OneofMessageValue
	}
	return nil
}

func (m *OneofMessage) GetRepeatedOneofValues() []*Oneof {
	if m != nil {
		return m.RepeatedOneofValues
	}
	return nil
}

func (m *OneofMessage) GetNormalOneofMessageValue() *Oneof {
	if m != nil {
		return m.NormalOneofMessageValue
	}
	return nil
}

func (m *OneofMessage) GetNormalRepeatedOneofValues() []*Oneof {
	if m != nil {
		return m.NormalRepeatedOneofValues
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*OneofMessage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _OneofMessage_OneofMarshaler, _OneofMessage_OneofUnmarshaler, _OneofMessage_OneofSizer, []interface{}{
		(*OneofMessage_Int32Value)(nil),
		(*OneofMessage_StringValue)(nil),
	}
}

func _OneofMessage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*OneofMessage)
	// oneof_value
	switch x := m.OneofValue.(type) {
	case *OneofMessage_Int32Value:
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Int32Value))
	case *OneofMessage_StringValue:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.StringValue)
	case nil:
	default:
		return fmt.Errorf("OneofMessage.OneofValue has unexpected type %T", x)
	}
	return nil
}

func _OneofMessage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*OneofMessage)
	switch tag {
	case 1: // oneof_value.int32_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.OneofValue = &OneofMessage_Int32Value{int32(x)}
		return true, err
	case 2: // oneof_value.string_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.OneofValue = &OneofMessage_StringValue{x}
		return true, err
	default:
		return false, nil
	}
}

func _OneofMessage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*OneofMessage)
	// oneof_value
	switch x := m.OneofValue.(type) {
	case *OneofMessage_Int32Value:
		n += proto.SizeVarint(1<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.Int32Value))
	case *OneofMessage_StringValue:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.StringValue)))
		n += len(x.StringValue)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type NormalOneofMessage struct {
	OneofMessageValue         *NormalOneof   `protobuf:"bytes,3,opt,name=oneof_message_value,json=oneofMessageValue" json:"oneof_message_value,omitempty"`
	RepeatedOneofValues       []*NormalOneof `protobuf:"bytes,4,rep,name=repeated_oneof_values,json=repeatedOneofValues" json:"repeated_oneof_values,omitempty"`
	NormalOneofMessageValue   *NormalOneof   `protobuf:"bytes,5,opt,name=normal_oneof_message_value,json=normalOneofMessageValue" json:"normal_oneof_message_value,omitempty"`
	NormalRepeatedOneofValues []*NormalOneof `protobuf:"bytes,6,rep,name=normal_repeated_oneof_values,json=normalRepeatedOneofValues" json:"normal_repeated_oneof_values,omitempty"`
}

func (m *NormalOneofMessage) Reset()                    { *m = NormalOneofMessage{} }
func (m *NormalOneofMessage) String() string            { return proto.CompactTextString(m) }
func (*NormalOneofMessage) ProtoMessage()               {}
func (*NormalOneofMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *NormalOneofMessage) GetOneofMessageValue() *NormalOneof {
	if m != nil {
		return m.OneofMessageValue
	}
	return nil
}

func (m *NormalOneofMessage) GetRepeatedOneofValues() []*NormalOneof {
	if m != nil {
		return m.RepeatedOneofValues
	}
	return nil
}

func (m *NormalOneofMessage) GetNormalOneofMessageValue() *NormalOneof {
	if m != nil {
		return m.NormalOneofMessageValue
	}
	return nil
}

func (m *NormalOneofMessage) GetNormalRepeatedOneofValues() []*NormalOneof {
	if m != nil {
		return m.NormalRepeatedOneofValues
	}
	return nil
}

type MapMessage struct {
	MappedValue             map[int32]string          `protobuf:"bytes,1,rep,name=mapped_value,json=mappedValue" json:"mapped_value,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MappedEnumValue         map[string]NumericEnum    `protobuf:"bytes,2,rep,name=mapped_enum_value,json=mappedEnumValue" json:"mapped_enum_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=kazegusuri.example.NumericEnum"`
	MappedNestedValue       map[string]*NestedMessage `protobuf:"bytes,3,rep,name=mapped_nested_value,json=mappedNestedValue" json:"mapped_nested_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NormalMappedValue       map[int32]string          `protobuf:"bytes,4,rep,name=normal_mapped_value,json=normalMappedValue" json:"normal_mapped_value,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NormalMappedEnumValue   map[string]NumericEnum    `protobuf:"bytes,5,rep,name=normal_mapped_enum_value,json=normalMappedEnumValue" json:"normal_mapped_enum_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=kazegusuri.example.NumericEnum"`
	NormalMappedNestedValue map[string]*NestedMessage `protobuf:"bytes,6,rep,name=normal_mapped_nested_value,json=normalMappedNestedValue" json:"normal_mapped_nested_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *MapMessage) Reset()                    { *m = MapMessage{} }
func (m *MapMessage) String() string            { return proto.CompactTextString(m) }
func (*MapMessage) ProtoMessage()               {}
func (*MapMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *MapMessage) GetMappedValue() map[int32]string {
	if m != nil {
		return m.MappedValue
	}
	return nil
}

func (m *MapMessage) GetMappedEnumValue() map[string]NumericEnum {
	if m != nil {
		return m.MappedEnumValue
	}
	return nil
}

func (m *MapMessage) GetMappedNestedValue() map[string]*NestedMessage {
	if m != nil {
		return m.MappedNestedValue
	}
	return nil
}

func (m *MapMessage) GetNormalMappedValue() map[int32]string {
	if m != nil {
		return m.NormalMappedValue
	}
	return nil
}

func (m *MapMessage) GetNormalMappedEnumValue() map[string]NumericEnum {
	if m != nil {
		return m.NormalMappedEnumValue
	}
	return nil
}

func (m *MapMessage) GetNormalMappedNestedValue() map[string]*NestedMessage {
	if m != nil {
		return m.NormalMappedNestedValue
	}
	return nil
}

type WellKnownTypeMessage struct {
	Duration  *google_protobuf1.Duration  `protobuf:"bytes,1,opt,name=duration" json:"duration,omitempty"`
	Timestamp *google_protobuf2.Timestamp `protobuf:"bytes,2,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *WellKnownTypeMessage) Reset()                    { *m = WellKnownTypeMessage{} }
func (m *WellKnownTypeMessage) String() string            { return proto.CompactTextString(m) }
func (*WellKnownTypeMessage) ProtoMessage()               {}
func (*WellKnownTypeMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *WellKnownTypeMessage) GetDuration() *google_protobuf1.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *WellKnownTypeMessage) GetTimestamp() *google_protobuf2.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func init() {
	proto.RegisterType((*SimpleMessage)(nil), "kazegusuri.example.SimpleMessage")
	proto.RegisterType((*NumberMessage)(nil), "kazegusuri.example.NumberMessage")
	proto.RegisterType((*RepeatedNumberMessage)(nil), "kazegusuri.example.RepeatedNumberMessage")
	proto.RegisterType((*NestedMessage)(nil), "kazegusuri.example.NestedMessage")
	proto.RegisterType((*NestedMessage_Nested)(nil), "kazegusuri.example.NestedMessage.Nested")
	proto.RegisterType((*EnumMessage)(nil), "kazegusuri.example.EnumMessage")
	proto.RegisterType((*Oneof)(nil), "kazegusuri.example.Oneof")
	proto.RegisterType((*NormalOneof)(nil), "kazegusuri.example.NormalOneof")
	proto.RegisterType((*OneofMessage)(nil), "kazegusuri.example.OneofMessage")
	proto.RegisterType((*NormalOneofMessage)(nil), "kazegusuri.example.NormalOneofMessage")
	proto.RegisterType((*MapMessage)(nil), "kazegusuri.example.MapMessage")
	proto.RegisterType((*WellKnownTypeMessage)(nil), "kazegusuri.example.WellKnownTypeMessage")
	proto.RegisterEnum("kazegusuri.example.NumericEnum", NumericEnum_name, NumericEnum_value)
	proto.RegisterEnum("kazegusuri.example.AliasedEnum", AliasedEnum_name, AliasedEnum_value)
	proto.RegisterEnum("kazegusuri.example.EnumMessage_Nested", EnumMessage_Nested_name, EnumMessage_Nested_value)
}

func init() { proto.RegisterFile("examples/example.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0xed, 0x72, 0xdb, 0x44,
	0x17, 0x8e, 0x2c, 0xdb, 0xb1, 0x8f, 0xe4, 0xc4, 0x51, 0xd2, 0xbc, 0x8e, 0xdf, 0x42, 0xb7, 0x66,
	0xa0, 0x4a, 0x3b, 0x75, 0x86, 0xf4, 0x83, 0x02, 0x03, 0x43, 0x4b, 0x3c, 0x94, 0x29, 0x55, 0x8a,
	0x9a, 0x34, 0x4c, 0xe8, 0x4c, 0x50, 0xea, 0x8d, 0xf1, 0xd4, 0x92, 0x3c, 0x5e, 0x0b, 0x9a, 0x5e,
	0x02, 0x37, 0xc0, 0xf0, 0x9b, 0xab, 0xe0, 0x6f, 0xb9, 0x04, 0xae, 0x84, 0x3b, 0x60, 0xa4, 0x95,
	0xb4, 0x67, 0x15, 0xf9, 0x8b, 0x29, 0xff, 0x2c, 0xed, 0xb3, 0xcf, 0x73, 0x3e, 0x1e, 0x1d, 0xad,
	0x05, 0x9b, 0xf4, 0x95, 0xe3, 0x0e, 0x07, 0x94, 0xed, 0xc4, 0x3f, 0xda, 0xc3, 0x91, 0x3f, 0xf6,
	0x0d, 0xe3, 0xa5, 0xf3, 0x9a, 0xf6, 0x02, 0x16, 0x8c, 0xfa, 0xed, 0x78, 0xa5, 0x59, 0x77, 0x3c,
	0xdf, 0x3b, 0x77, 0xfb, 0xaf, 0xe9, 0x88, 0xa3, 0x9a, 0xef, 0xf6, 0x7c, 0xbf, 0x37, 0xa0, 0x3b,
	0xd1, 0xd5, 0x69, 0x70, 0xb6, 0xd3, 0x0d, 0x46, 0xce, 0xb8, 0xef, 0x7b, 0xf1, 0xfa, 0x95, 0xec,
	0xfa, 0xb8, 0xef, 0x52, 0x36, 0x76, 0xdc, 0x21, 0x07, 0xb4, 0x1c, 0xa8, 0x3d, 0xed, 0x87, 0xe4,
	0x8f, 0x29, 0x63, 0x4e, 0x8f, 0x1a, 0xdb, 0xa0, 0xb3, 0xf1, 0xa8, 0xef, 0xf5, 0x4e, 0x7e, 0x72,
	0x06, 0x01, 0x6d, 0x28, 0x44, 0x31, 0xab, 0x0f, 0xca, 0x6f, 0xde, 0x5c, 0x29, 0x54, 0x14, 0x5b,
	0xe3, 0x6b, 0xcf, 0xc2, 0x25, 0xe3, 0x7d, 0x80, 0x53, 0xdf, 0x1f, 0xc4, 0xc0, 0x02, 0x51, 0xcc,
	0x4a, 0x0a, 0xac, 0x86, 0x2b, 0x11, 0xac, 0xf5, 0x5b, 0x11, 0x6a, 0x56, 0xe0, 0x9e, 0xd2, 0x51,
	0xa2, 0x71, 0x0d, 0xb4, 0xb3, 0x81, 0xef, 0x8c, 0x91, 0x44, 0x21, 0xdd, 0x09, 0xd1, 0x12, 0x57,
	0xd8, 0x06, 0xbd, 0xeb, 0x07, 0xa7, 0x03, 0x8a, 0x34, 0x14, 0x11, 0x0c, 0x5f, 0xe3, 0xd0, 0x6b,
	0xa0, 0xf5, 0xbd, 0xf1, 0xad, 0xdd, 0x18, 0xa9, 0x12, 0xc5, 0x2c, 0x09, 0xce, 0x68, 0x09, 0x03,
	0xef, 0xde, 0x8e, 0x81, 0x45, 0xa2, 0x98, 0xaa, 0x04, 0xbc, 0x7b, 0x3b, 0x15, 0x0f, 0x30, 0x65,
	0x89, 0x28, 0x66, 0x4d, 0x88, 0x07, 0x88, 0x33, 0x86, 0xa6, 0xa4, 0x65, 0xa2, 0x98, 0x45, 0x19,
	0x8a, 0x58, 0x19, 0x66, 0x5d, 0x26, 0x8a, 0xb9, 0x86, 0xea, 0x2b, 0xb3, 0x32, 0xcc, 0x5a, 0x21,
	0x8a, 0x69, 0xc8, 0xd0, 0x84, 0xf5, 0x06, 0xd4, 0xce, 0xfa, 0xaf, 0x68, 0x37, 0xa5, 0xad, 0x12,
	0xc5, 0x5c, 0x4e, 0xb1, 0x7a, 0xbc, 0x28, 0x83, 0x53, 0x62, 0x20, 0x8a, 0x59, 0xce, 0x80, 0x13,
	0xe6, 0x9b, 0xb0, 0xc2, 0x64, 0x6a, 0x8d, 0x28, 0xe6, 0x6a, 0x8a, 0xae, 0x31, 0x89, 0x3b, 0x85,
	0xa7, 0xe4, 0x3a, 0x51, 0xcc, 0x7a, 0x16, 0x1e, 0xb3, 0xb7, 0xfe, 0x28, 0xc2, 0x25, 0x9b, 0x0e,
	0xa9, 0x33, 0xa6, 0x5d, 0xd9, 0x23, 0xdb, 0xa0, 0x23, 0x8f, 0xb0, 0x86, 0x42, 0x54, 0x64, 0x12,
	0x4d, 0x98, 0x84, 0x85, 0xf9, 0x60, 0x97, 0xb0, 0x46, 0x81, 0xa8, 0xc8, 0x26, 0x3a, 0xb2, 0x09,
	0x0b, 0x79, 0x51, 0xf9, 0x59, 0x43, 0x25, 0x2a, 0x32, 0x8a, 0x26, 0xca, 0x9f, 0x40, 0x93, 0x44,
	0x58, 0xa3, 0x48, 0x54, 0x64, 0x15, 0x4d, 0x94, 0x3f, 0x0a, 0x21, 0x90, 0x68, 0x4b, 0x44, 0x45,
	0x66, 0xd1, 0x03, 0xcc, 0x1b, 0x83, 0x05, 0x71, 0x99, 0xa8, 0xc8, 0x2e, 0x7a, 0x90, 0x61, 0x66,
	0x12, 0xf3, 0x32, 0x51, 0x91, 0x61, 0x74, 0x96, 0x61, 0x66, 0x12, 0x73, 0x85, 0xa8, 0xc8, 0x32,
	0x3a, 0xc3, 0xcc, 0x37, 0x61, 0x45, 0x6a, 0x2c, 0x6b, 0x54, 0x89, 0x8a, 0x4c, 0x53, 0xc3, 0x8d,
	0x15, 0x70, 0x41, 0x0e, 0x44, 0x45, 0xb6, 0xa9, 0xe1, 0xc6, 0x32, 0x63, 0x07, 0x56, 0x59, 0x86,
	0x5e, 0x23, 0x2a, 0x32, 0xce, 0x0a, 0x93, 0xf9, 0xd3, 0x0d, 0x42, 0x40, 0x27, 0x2a, 0xb2, 0xce,
	0x8a, 0x64, 0x1d, 0xd6, 0xfa, 0x5b, 0x85, 0x9a, 0x45, 0xd9, 0x98, 0x76, 0x13, 0xcf, 0x3c, 0x05,
	0xdd, 0x8b, 0x6e, 0xa0, 0xc1, 0xa2, 0xed, 0x9a, 0xed, 0x8b, 0xa3, 0xb4, 0x2d, 0x6d, 0x8c, 0xaf,
	0x44, 0x6b, 0x39, 0x0b, 0x77, 0xf4, 0x19, 0x6c, 0x8e, 0x62, 0x87, 0x9e, 0x60, 0x76, 0x6e, 0xb3,
	0x7f, 0x43, 0xbf, 0x91, 0xf0, 0x59, 0x42, 0x86, 0x19, 0xdf, 0xc1, 0xba, 0xe7, 0x8f, 0x5c, 0x67,
	0x20, 0xa9, 0x44, 0x83, 0x6c, 0x01, 0x11, 0x7b, 0x8d, 0x93, 0x20, 0x6a, 0xe3, 0x25, 0xbc, 0x13,
	0x33, 0x4f, 0x48, 0xa4, 0xb8, 0x58, 0x22, 0x76, 0x93, 0xd3, 0xd9, 0x39, 0x69, 0x34, 0x9f, 0x43,
	0x99, 0x5f, 0x67, 0x27, 0xb2, 0x32, 0x71, 0x22, 0x67, 0x5f, 0x39, 0x85, 0x89, 0xaf, 0x9c, 0xd6,
	0xef, 0x45, 0xd0, 0x3a, 0x5e, 0xe0, 0x26, 0x1d, 0x3f, 0x04, 0xc3, 0x0b, 0x5c, 0x3a, 0xea, 0xbf,
	0x38, 0xa1, 0x5e, 0xe0, 0x22, 0xa9, 0x95, 0xdd, 0x2b, 0xb9, 0xf9, 0x70, 0x74, 0xc8, 0x91, 0x2a,
	0xd4, 0x3d, 0x71, 0x93, 0x47, 0xf4, 0x23, 0x5c, 0x16, 0xa5, 0xba, 0xc0, 0xcf, 0x3b, 0xbf, 0x80,
	0xc0, 0xd6, 0x48, 0x8c, 0x38, 0x49, 0x88, 0x85, 0x09, 0x38, 0x83, 0xbe, 0xc3, 0x68, 0x17, 0x27,
	0xa0, 0x4e, 0x4e, 0xe0, 0x3e, 0x47, 0xcb, 0x09, 0x38, 0xe2, 0x26, 0x4f, 0xe0, 0x18, 0xd6, 0xe2,
	0x16, 0x23, 0xd6, 0x62, 0xc4, 0xfa, 0x41, 0x1e, 0x2b, 0xaa, 0x69, 0xd6, 0xad, 0xab, 0x9c, 0x48,
	0x70, 0xbb, 0xf0, 0xff, 0xac, 0x8f, 0x70, 0x6d, 0x4a, 0x51, 0x6d, 0x16, 0x55, 0x69, 0xc8, 0xcf,
	0x84, 0xa8, 0x50, 0xeb, 0xc3, 0xd4, 0x50, 0x1a, 0x2c, 0x1f, 0x5a, 0x8f, 0xac, 0xfd, 0x23, 0xab,
	0xbe, 0x14, 0x5e, 0x3c, 0xe9, 0x58, 0x7b, 0x5f, 0x5b, 0x5f, 0xd5, 0x15, 0xa3, 0x06, 0xd5, 0x2f,
	0xf7, 0x1f, 0x3f, 0xf9, 0xa6, 0x73, 0xd0, 0xd9, 0xab, 0x17, 0x5a, 0x1e, 0x94, 0xf6, 0x3d, 0xea,
	0x9f, 0x19, 0xdb, 0x53, 0x2c, 0xf8, 0x70, 0x49, 0x32, 0xe1, 0x8d, 0x69, 0x26, 0x7c, 0xb8, 0x24,
	0xd9, 0xf0, 0x41, 0x0d, 0x34, 0x3f, 0x14, 0xe0, 0xd8, 0x56, 0x17, 0x34, 0x2b, 0x7a, 0x22, 0xb8,
	0xea, 0xd5, 0x1c, 0xd5, 0x8c, 0xda, 0x7b, 0x79, 0x6a, 0x33, 0x54, 0xfe, 0x52, 0x41, 0x8f, 0x04,
	0xc4, 0x2b, 0xf2, 0x3f, 0xc9, 0xce, 0xf8, 0x16, 0xd6, 0xb9, 0xae, 0xcb, 0x85, 0xa4, 0x49, 0xb4,
	0x95, 0xd7, 0xd8, 0x28, 0xac, 0xb4, 0x97, 0x6b, 0x3e, 0x8a, 0x92, 0x53, 0x1e, 0xc2, 0xa5, 0xd4,
	0x33, 0x28, 0xa7, 0x64, 0xf4, 0xcc, 0x41, 0xba, 0x9e, 0xec, 0x8f, 0x6e, 0xc7, 0x4f, 0xcf, 0x33,
	0x88, 0x47, 0xd1, 0x49, 0x5e, 0xc0, 0xa5, 0x19, 0x01, 0xdb, 0xff, 0xf3, 0x44, 0xd7, 0xa4, 0x70,
	0x8f, 0xe1, 0x72, 0x76, 0x62, 0x4a, 0x51, 0x97, 0x67, 0x44, 0x6d, 0x6f, 0xc9, 0x13, 0x12, 0xc5,
	0x9c, 0xed, 0xea, 0x2f, 0x2a, 0x18, 0xd6, 0x85, 0x30, 0x8c, 0xa3, 0x69, 0x3d, 0xc8, 0x1f, 0x3c,
	0x82, 0x64, 0x5a, 0x27, 0xbe, 0x9f, 0xde, 0x89, 0xb9, 0xa9, 0x73, 0xfb, 0xf1, 0x7c, 0x8e, 0x7e,
	0xcc, 0x52, 0x98, 0xdc, 0x95, 0x1f, 0xe6, 0xea, 0xca, 0x4c, 0xfe, 0xc9, 0xbd, 0x69, 0xfd, 0x59,
	0x05, 0x78, 0xec, 0x0c, 0x93, 0x26, 0x1c, 0x83, 0xee, 0x3a, 0xc3, 0x21, 0x3a, 0x4f, 0x84, 0x02,
	0x3b, 0x79, 0x02, 0x62, 0x57, 0xf8, 0x73, 0x18, 0xbf, 0x0e, 0x3b, 0xde, 0x78, 0x74, 0x2e, 0xde,
	0x64, 0xae, 0x58, 0x31, 0x7a, 0xb0, 0x16, 0x73, 0xa3, 0x09, 0xcd, 0x4f, 0x14, 0xb7, 0xe6, 0x12,
	0x48, 0x47, 0xa4, 0x2c, 0xb2, 0xea, 0xca, 0xab, 0x86, 0x0b, 0xeb, 0xb1, 0x50, 0xe6, 0x5c, 0x11,
	0x4a, 0xdd, 0x99, 0x4b, 0x0a, 0xbd, 0xe0, 0x65, 0xb1, 0x38, 0x05, 0x7c, 0xd8, 0xa0, 0xe9, 0x31,
	0x46, 0x2a, 0x5d, 0x71, 0x2e, 0x39, 0xde, 0xa6, 0x6c, 0x01, 0x93, 0x33, 0x0d, 0xba, 0x6f, 0x8c,
	0xa0, 0x21, 0xcb, 0xa0, 0x2a, 0x96, 0x22, 0xad, 0x8f, 0x17, 0xd0, 0x92, 0x6b, 0x69, 0x5f, 0xf2,
	0xf2, 0xd6, 0x8c, 0x57, 0xa9, 0xbb, 0xf3, 0x0a, 0xca, 0xdd, 0xf7, 0xe9, 0x02, 0xaa, 0xd9, 0xb2,
	0x26, 0xce, 0xbf, 0xb0, 0xda, 0xfc, 0x1c, 0xea, 0xd9, 0xa2, 0x18, 0x75, 0x50, 0x5f, 0xd2, 0x73,
	0x3e, 0xf5, 0xed, 0xf0, 0xa7, 0xb1, 0x01, 0x25, 0x34, 0xdd, 0x6d, 0x7e, 0xf1, 0x49, 0xe1, 0x9e,
	0xd2, 0x7c, 0x01, 0x1b, 0x79, 0x89, 0x62, 0x8e, 0x2a, 0xe7, 0xb8, 0x83, 0x39, 0x66, 0x1f, 0x71,
	0xb0, 0x48, 0x0f, 0x36, 0xf3, 0xf3, 0xca, 0x91, 0xf9, 0x08, 0xcb, 0x68, 0xbb, 0x57, 0x67, 0x1e,
	0x3d, 0xb1, 0xd0, 0x1e, 0x6c, 0xe6, 0x1b, 0x65, 0xa1, 0x9a, 0xf4, 0xa1, 0x39, 0xd9, 0x02, 0x6f,
	0xb7, 0x32, 0x2e, 0x5c, 0x9e, 0xd6, 0xf7, 0xb7, 0x5c, 0x9f, 0xd6, 0xaf, 0x0a, 0x6c, 0x1c, 0xd1,
	0xc1, 0xe0, 0x91, 0xe7, 0xff, 0xec, 0x1d, 0x9c, 0x0f, 0xd3, 0x6f, 0x3b, 0x9f, 0x41, 0x25, 0xf9,
	0x3e, 0x14, 0xff, 0x37, 0xda, 0x6a, 0xf3, 0x0f, 0x44, 0xed, 0xe4, 0x03, 0x51, 0x7b, 0x2f, 0x06,
	0xa4, 0xcf, 0x78, 0xba, 0xc5, 0xf8, 0x02, 0xaa, 0xe9, 0xe7, 0xa3, 0x38, 0xb0, 0xe6, 0x85, 0xfd,
	0x07, 0x09, 0x42, 0x7c, 0x0a, 0x4a, 0x37, 0x5d, 0xdf, 0x06, 0x0d, 0x95, 0xc8, 0xa8, 0x40, 0xf1,
	0xb8, 0x63, 0xef, 0xd7, 0x97, 0x8c, 0x65, 0x50, 0xf7, 0xad, 0x4e, 0x5d, 0x09, 0x7f, 0x1c, 0x1c,
	0xed, 0xd7, 0x0b, 0xd7, 0xef, 0x81, 0x86, 0x8e, 0xba, 0x17, 0xce, 0x7e, 0x4f, 0x0f, 0xee, 0xdb,
	0xe1, 0x61, 0x4f, 0x09, 0x2f, 0xec, 0x43, 0xcb, 0x8a, 0x0e, 0x82, 0xcd, 0x42, 0x5d, 0x79, 0x00,
	0xc7, 0x95, 0xe4, 0x9b, 0xda, 0x69, 0x39, 0x8a, 0xeb, 0xd6, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x4d, 0x0f, 0x69, 0xdf, 0x66, 0x13, 0x00, 0x00,
}
